
// This file has been generated by the GUI designer. Do not modify.
namespace NewRestoran
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.Notebook notebookMain;

		private global::Gtk.HBox hbox1;

		private global::CustomWidgetLibrary.FixedRestoranSheme fixedrestoransheme;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Button buttonSearch;

		private global::Gtk.Entry entrySearch;

		private global::Gtk.ScrolledWindow GtkScrolledWindowNarudzbe;

		private global::Gtk.NodeView nodeviewNarudzbe;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HBox hbox7;

		private global::Gtk.ComboBox comboboxSveTrenutna;

		private global::Gtk.ComboBox comboboxStatus;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.ScrolledWindow GtkScrolledWindowStatusStavaka;

		private global::Gtk.NodeView nodeviewNarudzbeStatus;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label6;

		private global::Gtk.Label labelBroj;

		private global::Gtk.VSeparator vseparator1;

		private global::Gtk.Entry entrySearch1;

		private global::Gtk.Button button1;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label label8;

		private global::Gtk.Label labelDatum;

		private global::Gtk.HBox hbox10;

		private global::Gtk.VBox vboxNarudzbeButtons;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Button buttonDodaj;

		private global::Gtk.Button buttonStavke;

		private global::Gtk.Button buttonNarudzbeUp;

		private global::Gtk.Button buttonNarudzbeDown;

		private global::Gtk.Button buttonNarudzbeChange;

		private global::Gtk.Button buttonDeleteNarudzba;

		private global::Gtk.Button buttonZakljuci;

		private global::Gtk.VBox vboxStatusButtons;

		private global::Gtk.Button buttonDeliver;

		private global::Gtk.Button buttonStatusDown;

		private global::Gtk.Button buttonStatusUp;

		private global::Gtk.Button buttonFinishOrder;

		private global::Gtk.Button buttonTakeOrder;

		private global::Gtk.Label label2;

		private global::Gtk.Label label5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NewRestoran.MainWindow
			this.Name = "NewRestoran.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child NewRestoran.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this..AddUiFromString("<ui><menubar name=\'menubar1\'><menuitem/><menuitem/><menuitem/><menuitem/><menuite" +
					"m/><menuitem/></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this..GetWidget("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add(this.menubar1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this..AddUiFromString("<ui><toolbar name=\'toolbar1\'><toolitem/><toolitem/><toolitem/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this..GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(2));
			this.vbox1.Add(this.toolbar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebookMain = new global::Gtk.Notebook();
			this.notebookMain.CanFocus = true;
			this.notebookMain.Name = "notebookMain";
			this.notebookMain.CurrentPage = 0;
			this.notebookMain.EnablePopup = true;
			this.notebookMain.Scrollable = true;
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixedrestoransheme = new global::CustomWidgetLibrary.FixedRestoranSheme();
			this.fixedrestoransheme.Events = ((global::Gdk.EventMask)(256));
			this.fixedrestoransheme.Name = "fixedrestoransheme";
			this.fixedrestoransheme.ToolboxShown = false;
			this.hbox1.Add(this.fixedrestoransheme);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixedrestoransheme]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonSearch = new global::Gtk.Button();
			this.buttonSearch.WidthRequest = 39;
			this.buttonSearch.HeightRequest = 25;
			this.buttonSearch.CanFocus = true;
			this.buttonSearch.Name = "buttonSearch";
			this.buttonSearch.UseUnderline = true;
			global::Gtk.Image w4 = new global::Gtk.Image();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-find", global::Gtk.IconSize.Menu);
			this.buttonSearch.Image = w4;
			this.hbox6.Add(this.buttonSearch);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.buttonSearch]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entrySearch = new global::Gtk.Entry();
			this.entrySearch.WidthRequest = 180;
			this.entrySearch.CanFocus = true;
			this.entrySearch.Name = "entrySearch";
			this.entrySearch.IsEditable = true;
			this.entrySearch.InvisibleChar = '●';
			this.hbox6.Add(this.entrySearch);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entrySearch]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 1;
			w6.Expand = false;
			this.vbox3.Add(this.hbox6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox6]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindowNarudzbe = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindowNarudzbe.Name = "GtkScrolledWindowNarudzbe";
			this.GtkScrolledWindowNarudzbe.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindowNarudzbe.Gtk.Container+ContainerChild
			this.nodeviewNarudzbe = new global::Gtk.NodeView();
			this.nodeviewNarudzbe.WidthRequest = 600;
			this.nodeviewNarudzbe.CanFocus = true;
			this.nodeviewNarudzbe.Name = "nodeviewNarudzbe";
			this.nodeviewNarudzbe.Reorderable = true;
			this.nodeviewNarudzbe.RulesHint = true;
			this.nodeviewNarudzbe.SearchColumn = 0;
			this.GtkScrolledWindowNarudzbe.Add(this.nodeviewNarudzbe);
			this.vbox3.Add(this.GtkScrolledWindowNarudzbe);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindowNarudzbe]));
			w9.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.HeightRequest = 12;
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator1]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.comboboxSveTrenutna = new global::Gtk.ComboBox();
			this.comboboxSveTrenutna.WidthRequest = 180;
			this.comboboxSveTrenutna.Name = "comboboxSveTrenutna";
			this.hbox7.Add(this.comboboxSveTrenutna);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.comboboxSveTrenutna]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.comboboxStatus = new global::Gtk.ComboBox();
			this.comboboxStatus.WidthRequest = 180;
			this.comboboxStatus.Name = "comboboxStatus";
			this.hbox7.Add(this.comboboxStatus);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.comboboxStatus]));
			w12.PackType = ((global::Gtk.PackType)(1));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox3.Add(this.hbox7);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.HeightRequest = 12;
			this.hseparator2.Name = "hseparator2";
			this.vbox3.Add(this.hseparator2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator2]));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindowStatusStavaka = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindowStatusStavaka.Name = "GtkScrolledWindowStatusStavaka";
			this.GtkScrolledWindowStatusStavaka.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindowStatusStavaka.Gtk.Container+ContainerChild
			this.nodeviewNarudzbeStatus = new global::Gtk.NodeView();
			this.nodeviewNarudzbeStatus.WidthRequest = 600;
			this.nodeviewNarudzbeStatus.CanFocus = true;
			this.nodeviewNarudzbeStatus.Name = "nodeviewNarudzbeStatus";
			this.nodeviewNarudzbeStatus.Reorderable = true;
			this.nodeviewNarudzbeStatus.RulesHint = true;
			this.nodeviewNarudzbeStatus.SearchColumn = 0;
			this.GtkScrolledWindowStatusStavaka.Add(this.nodeviewNarudzbeStatus);
			this.vbox3.Add(this.GtkScrolledWindowStatusStavaka);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindowStatusStavaka]));
			w16.Position = 5;
			this.hbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Broj:");
			this.hbox8.Add(this.label6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label6]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.labelBroj = new global::Gtk.Label();
			this.labelBroj.Name = "labelBroj";
			this.labelBroj.LabelProp = "";
			this.hbox8.Add(this.labelBroj);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.labelBroj]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.WidthRequest = 13;
			this.vseparator1.Name = "vseparator1";
			this.hbox8.Add(this.vseparator1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.vseparator1]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.entrySearch1 = new global::Gtk.Entry();
			this.entrySearch1.WidthRequest = 120;
			this.entrySearch1.CanFocus = true;
			this.entrySearch1.Name = "entrySearch1";
			this.entrySearch1.IsEditable = true;
			this.entrySearch1.InvisibleChar = '●';
			this.hbox8.Add(this.entrySearch1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.entrySearch1]));
			w21.Position = 3;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button();
			this.button1.WidthRequest = 30;
			this.button1.HeightRequest = 25;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			global::Gtk.Image w22 = new global::Gtk.Image();
			w22.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-find", global::Gtk.IconSize.Button);
			this.button1.Image = w22;
			this.hbox8.Add(this.button1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.button1]));
			w23.Position = 4;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox2.Add(this.hbox8);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox8]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Datum:");
			this.hbox9.Add(this.label8);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label8]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.labelDatum = new global::Gtk.Label();
			this.labelDatum.Name = "labelDatum";
			this.labelDatum.LabelProp = "";
			this.hbox9.Add(this.labelDatum);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.labelDatum]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox2.Add(this.hbox9);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox9]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			this.vbox2.Add(this.hbox10);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox10]));
			w28.Position = 2;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vboxNarudzbeButtons = new global::Gtk.VBox();
			this.vboxNarudzbeButtons.Name = "vboxNarudzbeButtons";
			this.vboxNarudzbeButtons.Spacing = 23;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.HeightRequest = 7;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vboxNarudzbeButtons.Add(this.fixed1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.fixed1]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonDodaj = new global::Gtk.Button();
			this.buttonDodaj.CanFocus = true;
			this.buttonDodaj.Name = "buttonDodaj";
			this.buttonDodaj.UseUnderline = true;
			this.buttonDodaj.FocusOnClick = false;
			global::Gtk.Image w31 = new global::Gtk.Image();
			w31.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.add-order.png");
			this.buttonDodaj.Image = w31;
			this.vboxNarudzbeButtons.Add(this.buttonDodaj);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonDodaj]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonStavke = new global::Gtk.Button();
			this.buttonStavke.CanFocus = true;
			this.buttonStavke.Name = "buttonStavke";
			this.buttonStavke.UseUnderline = true;
			this.buttonStavke.FocusOnClick = false;
			global::Gtk.Image w33 = new global::Gtk.Image();
			w33.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.add-item.png");
			this.buttonStavke.Image = w33;
			this.vboxNarudzbeButtons.Add(this.buttonStavke);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonStavke]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonNarudzbeUp = new global::Gtk.Button();
			this.buttonNarudzbeUp.CanFocus = true;
			this.buttonNarudzbeUp.Name = "buttonNarudzbeUp";
			this.buttonNarudzbeUp.UseUnderline = true;
			this.buttonNarudzbeUp.FocusOnClick = false;
			global::Gtk.Image w35 = new global::Gtk.Image();
			w35.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.up.png");
			this.buttonNarudzbeUp.Image = w35;
			this.vboxNarudzbeButtons.Add(this.buttonNarudzbeUp);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonNarudzbeUp]));
			w36.Position = 3;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonNarudzbeDown = new global::Gtk.Button();
			this.buttonNarudzbeDown.CanFocus = true;
			this.buttonNarudzbeDown.Name = "buttonNarudzbeDown";
			this.buttonNarudzbeDown.UseUnderline = true;
			this.buttonNarudzbeDown.FocusOnClick = false;
			global::Gtk.Image w37 = new global::Gtk.Image();
			w37.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.down.png");
			this.buttonNarudzbeDown.Image = w37;
			this.vboxNarudzbeButtons.Add(this.buttonNarudzbeDown);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonNarudzbeDown]));
			w38.Position = 4;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonNarudzbeChange = new global::Gtk.Button();
			this.buttonNarudzbeChange.CanFocus = true;
			this.buttonNarudzbeChange.Name = "buttonNarudzbeChange";
			this.buttonNarudzbeChange.UseUnderline = true;
			this.buttonNarudzbeChange.FocusOnClick = false;
			global::Gtk.Image w39 = new global::Gtk.Image();
			w39.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.change.png");
			this.buttonNarudzbeChange.Image = w39;
			this.vboxNarudzbeButtons.Add(this.buttonNarudzbeChange);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonNarudzbeChange]));
			w40.Position = 5;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonDeleteNarudzba = new global::Gtk.Button();
			this.buttonDeleteNarudzba.CanFocus = true;
			this.buttonDeleteNarudzba.Name = "buttonDeleteNarudzba";
			this.buttonDeleteNarudzba.UseUnderline = true;
			this.buttonDeleteNarudzba.FocusOnClick = false;
			global::Gtk.Image w41 = new global::Gtk.Image();
			w41.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.delete.png");
			this.buttonDeleteNarudzba.Image = w41;
			this.vboxNarudzbeButtons.Add(this.buttonDeleteNarudzba);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonDeleteNarudzba]));
			w42.Position = 6;
			w42.Expand = false;
			w42.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonZakljuci = new global::Gtk.Button();
			this.buttonZakljuci.CanFocus = true;
			this.buttonZakljuci.Name = "buttonZakljuci";
			this.buttonZakljuci.UseUnderline = true;
			this.buttonZakljuci.FocusOnClick = false;
			global::Gtk.Image w43 = new global::Gtk.Image();
			w43.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.lock.png");
			this.buttonZakljuci.Image = w43;
			this.vboxNarudzbeButtons.Add(this.buttonZakljuci);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonZakljuci]));
			w44.Position = 7;
			w44.Expand = false;
			w44.Fill = false;
			this.hbox1.Add(this.vboxNarudzbeButtons);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vboxNarudzbeButtons]));
			w45.Position = 3;
			w45.Expand = false;
			w45.Fill = false;
			w45.Padding = ((uint)(32));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vboxStatusButtons = new global::Gtk.VBox();
			this.vboxStatusButtons.Name = "vboxStatusButtons";
			this.vboxStatusButtons.Spacing = 23;
			// Container child vboxStatusButtons.Gtk.Box+BoxChild
			this.buttonDeliver = new global::Gtk.Button();
			this.buttonDeliver.CanFocus = true;
			this.buttonDeliver.Name = "buttonDeliver";
			this.buttonDeliver.UseUnderline = true;
			this.buttonDeliver.FocusOnClick = false;
			global::Gtk.Image w46 = new global::Gtk.Image();
			w46.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.delivering.png");
			this.buttonDeliver.Image = w46;
			this.vboxStatusButtons.Add(this.buttonDeliver);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vboxStatusButtons[this.buttonDeliver]));
			w47.PackType = ((global::Gtk.PackType)(1));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vboxStatusButtons.Gtk.Box+BoxChild
			this.buttonStatusDown = new global::Gtk.Button();
			this.buttonStatusDown.CanFocus = true;
			this.buttonStatusDown.Name = "buttonStatusDown";
			this.buttonStatusDown.UseUnderline = true;
			this.buttonStatusDown.FocusOnClick = false;
			global::Gtk.Image w48 = new global::Gtk.Image();
			w48.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.down.png");
			this.buttonStatusDown.Image = w48;
			this.vboxStatusButtons.Add(this.buttonStatusDown);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vboxStatusButtons[this.buttonStatusDown]));
			w49.PackType = ((global::Gtk.PackType)(1));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			// Container child vboxStatusButtons.Gtk.Box+BoxChild
			this.buttonStatusUp = new global::Gtk.Button();
			this.buttonStatusUp.CanFocus = true;
			this.buttonStatusUp.Name = "buttonStatusUp";
			this.buttonStatusUp.UseUnderline = true;
			this.buttonStatusUp.FocusOnClick = false;
			global::Gtk.Image w50 = new global::Gtk.Image();
			w50.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.up.png");
			this.buttonStatusUp.Image = w50;
			this.vboxStatusButtons.Add(this.buttonStatusUp);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vboxStatusButtons[this.buttonStatusUp]));
			w51.PackType = ((global::Gtk.PackType)(1));
			w51.Position = 2;
			w51.Expand = false;
			w51.Fill = false;
			// Container child vboxStatusButtons.Gtk.Box+BoxChild
			this.buttonFinishOrder = new global::Gtk.Button();
			this.buttonFinishOrder.CanFocus = true;
			this.buttonFinishOrder.Name = "buttonFinishOrder";
			this.buttonFinishOrder.UseUnderline = true;
			this.buttonFinishOrder.FocusOnClick = false;
			global::Gtk.Image w52 = new global::Gtk.Image();
			w52.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.order-ready.png");
			this.buttonFinishOrder.Image = w52;
			this.vboxStatusButtons.Add(this.buttonFinishOrder);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vboxStatusButtons[this.buttonFinishOrder]));
			w53.PackType = ((global::Gtk.PackType)(1));
			w53.Position = 3;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vboxStatusButtons.Gtk.Box+BoxChild
			this.buttonTakeOrder = new global::Gtk.Button();
			this.buttonTakeOrder.CanFocus = true;
			this.buttonTakeOrder.Name = "buttonTakeOrder";
			this.buttonTakeOrder.UseUnderline = true;
			this.buttonTakeOrder.FocusOnClick = false;
			global::Gtk.Image w54 = new global::Gtk.Image();
			w54.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.take-order.png");
			this.buttonTakeOrder.Image = w54;
			this.vboxStatusButtons.Add(this.buttonTakeOrder);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vboxStatusButtons[this.buttonTakeOrder]));
			w55.PackType = ((global::Gtk.PackType)(1));
			w55.Position = 4;
			w55.Expand = false;
			w55.Fill = false;
			this.hbox1.Add(this.vboxStatusButtons);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vboxStatusButtons]));
			w56.Position = 4;
			w56.Expand = false;
			w56.Fill = false;
			w56.Padding = ((uint)(32));
			this.notebookMain.Add(this.hbox1);
			// Notebook tab
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("llll");
			this.notebookMain.SetTabLabel(this.hbox1, this.label2);
			this.label2.ShowAll();
			// Notebook tab
			global::Gtk.Label w58 = new global::Gtk.Label();
			w58.Visible = true;
			this.notebookMain.Add(w58);
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("page2");
			this.notebookMain.SetTabLabel(w58, this.label5);
			this.label5.ShowAll();
			this.vbox1.Add(this.notebookMain);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebookMain]));
			w59.Position = 2;
			w59.Padding = ((uint)(10));
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1995;
			this.DefaultHeight = 1087;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.comboboxSveTrenutna.Changed += new global::System.EventHandler(this.OnComboboxSveTrenutnaChanged);
			this.comboboxStatus.Changed += new global::System.EventHandler(this.OnComboboxStatusChanged);
			this.buttonDodaj.Clicked += new global::System.EventHandler(this.OnButtonDodajClicked);
			this.buttonStavke.Clicked += new global::System.EventHandler(this.OnButtonStavkeClicked);
			this.buttonNarudzbeUp.Clicked += new global::System.EventHandler(this.OnButtonNarudzbeUpClicked);
			this.buttonNarudzbeDown.Clicked += new global::System.EventHandler(this.OnButtonNarudzbeDownClicked);
			this.buttonNarudzbeChange.Clicked += new global::System.EventHandler(this.OnButtonNarudzbeChangeClicked);
			this.buttonDeleteNarudzba.Clicked += new global::System.EventHandler(this.OnButtonDeleteNarudzbaClicked);
			this.buttonZakljuci.Clicked += new global::System.EventHandler(this.OnButtonZakljuciClicked);
			this.buttonTakeOrder.Clicked += new global::System.EventHandler(this.OnButtonTakeOrderClicked);
			this.buttonFinishOrder.Clicked += new global::System.EventHandler(this.OnButtonFinishOrderClicked);
			this.buttonStatusUp.Clicked += new global::System.EventHandler(this.OnButtonStatusUpClicked);
			this.buttonStatusDown.Clicked += new global::System.EventHandler(this.OnButtonStatusDownClicked);
			this.buttonDeliver.Clicked += new global::System.EventHandler(this.OnButtonDeliverClicked);
		}
	}
}
