
// This file has been generated by the GUI designer. Do not modify.
namespace NewRestoran
{
	public partial class CalendarWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Calendar calendar;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Button buttonOdustani;

		private global::Gtk.Button buttonOdaberi;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NewRestoran.CalendarWindow
			this.Name = "NewRestoran.CalendarWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Kalendar");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.logo.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(2));
			this.Modal = true;
			this.BorderWidth = ((uint)(10));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child NewRestoran.CalendarWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.calendar = new global::Gtk.Calendar();
			this.calendar.CanFocus = true;
			this.calendar.Name = "calendar";
			this.calendar.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox1.Add(this.calendar);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.calendar]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 20;
			this.hbox12.BorderWidth = ((uint)(25));
			// Container child hbox12.Gtk.Box+BoxChild
			this.buttonOdustani = new global::Gtk.Button();
			this.buttonOdustani.WidthRequest = 150;
			this.buttonOdustani.HeightRequest = 50;
			this.buttonOdustani.CanFocus = true;
			this.buttonOdustani.Name = "buttonOdustani";
			this.buttonOdustani.UseUnderline = true;
			this.buttonOdustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			global::Gtk.Image w2 = new global::Gtk.Image();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Button);
			this.buttonOdustani.Image = w2;
			this.hbox12.Add(this.buttonOdustani);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.buttonOdustani]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.buttonOdaberi = new global::Gtk.Button();
			this.buttonOdaberi.WidthRequest = 150;
			this.buttonOdaberi.HeightRequest = 50;
			this.buttonOdaberi.CanFocus = true;
			this.buttonOdaberi.Name = "buttonOdaberi";
			this.buttonOdaberi.UseUnderline = true;
			this.buttonOdaberi.Label = global::Mono.Unix.Catalog.GetString("Odaberi");
			global::Gtk.Image w4 = new global::Gtk.Image();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Button);
			this.buttonOdaberi.Image = w4;
			this.hbox12.Add(this.buttonOdaberi);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.buttonOdaberi]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add(this.hbox12);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox12]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 390;
			this.DefaultHeight = 296;
			this.Show();
			this.buttonOdustani.Clicked += new global::System.EventHandler(this.OnButtonOdustaniClicked);
			this.buttonOdaberi.Clicked += new global::System.EventHandler(this.OnButtonOdaberiClicked);
		}
	}
}
