
// This file has been generated by the GUI designer. Do not modify.
namespace NewRestoran
{
	public partial class LoginWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label tittleLabel;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label usernameLabel;

		private global::Gtk.Entry imeEntry;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label passwordLabel;

		private global::Gtk.Entry passwordEntry;

		private global::Gtk.HButtonBox hbuttonbox2;

		private global::Gtk.Button cancelLoginButton;

		private global::Gtk.Button loginButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NewRestoran.LoginWindow
			this.Name = "NewRestoran.LoginWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Login");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.logo.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.BorderWidth = ((uint)(30));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child NewRestoran.LoginWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 15;
			// Container child vbox1.Gtk.Box+BoxChild
			this.tittleLabel = new global::Gtk.Label();
			this.tittleLabel.HeightRequest = 42;
			this.tittleLabel.Name = "tittleLabel";
			this.tittleLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Prijava");
			this.vbox1.Add(this.tittleLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.tittleLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.usernameLabel = new global::Gtk.Label();
			this.usernameLabel.WidthRequest = 65;
			this.usernameLabel.Name = "usernameLabel";
			this.usernameLabel.Xalign = 1F;
			this.usernameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Ime:");
			this.hbox1.Add(this.usernameLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.usernameLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(10));
			// Container child hbox1.Gtk.Box+BoxChild
			this.imeEntry = new global::Gtk.Entry();
			this.imeEntry.CanFocus = true;
			this.imeEntry.Name = "imeEntry";
			this.imeEntry.IsEditable = true;
			this.imeEntry.InvisibleChar = '●';
			this.hbox1.Add(this.imeEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.imeEntry]));
			w3.Position = 1;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.passwordLabel = new global::Gtk.Label();
			this.passwordLabel.WidthRequest = 65;
			this.passwordLabel.Name = "passwordLabel";
			this.passwordLabel.Xalign = 1F;
			this.passwordLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Lozinka:");
			this.hbox2.Add(this.passwordLabel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.passwordLabel]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(10));
			// Container child hbox2.Gtk.Box+BoxChild
			this.passwordEntry = new global::Gtk.Entry();
			this.passwordEntry.CanFocus = true;
			this.passwordEntry.Name = "passwordEntry";
			this.passwordEntry.IsEditable = true;
			this.passwordEntry.Visibility = false;
			this.passwordEntry.InvisibleChar = '●';
			this.hbox2.Add(this.passwordEntry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.passwordEntry]));
			w6.Position = 1;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.Homogeneous = true;
			this.hbuttonbox2.Spacing = 3;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.cancelLoginButton = new global::Gtk.Button();
			this.cancelLoginButton.WidthRequest = 134;
			this.cancelLoginButton.HeightRequest = 43;
			this.cancelLoginButton.CanFocus = true;
			this.cancelLoginButton.Name = "cancelLoginButton";
			this.cancelLoginButton.UseUnderline = true;
			this.cancelLoginButton.Relief = ((global::Gtk.ReliefStyle)(1));
			this.cancelLoginButton.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			global::Gtk.Image w8 = new global::Gtk.Image();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Button);
			this.cancelLoginButton.Image = w8;
			this.hbuttonbox2.Add(this.cancelLoginButton);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.cancelLoginButton]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.loginButton = new global::Gtk.Button();
			this.loginButton.CanFocus = true;
			this.loginButton.Name = "loginButton";
			this.loginButton.UseUnderline = true;
			this.loginButton.Relief = ((global::Gtk.ReliefStyle)(1));
			this.loginButton.Label = global::Mono.Unix.Catalog.GetString("Prijava");
			global::Gtk.Image w10 = new global::Gtk.Image();
			w10.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Button);
			this.loginButton.Image = w10;
			this.hbuttonbox2.Add(this.loginButton);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.loginButton]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox1.Add(this.hbuttonbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox2]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			w12.Padding = ((uint)(7));
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 378;
			this.DefaultHeight = 288;
			this.Show();
			this.cancelLoginButton.Clicked += new global::System.EventHandler(this.OnCancelLoginButtonClicked);
			this.loginButton.Clicked += new global::System.EventHandler(this.OnLoginButtonClicked);
		}
	}
}
