
// This file has been generated by the GUI designer. Do not modify.
namespace NewRestoran {
	public partial class ArtikliWindow {
		private global::Gtk.HBox hbox2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeviewArtikli;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label1;

		private global::Gtk.Entry entrySifra;

		private global::Gtk.VSeparator vseparator1;

		private global::Gtk.Entry entry3;

		private global::Gtk.Button buttonSearch;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label2;

		private global::Gtk.Entry entryNaziv;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label3;

		private global::Gtk.Entry entryDuziNaziv;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label4;

		private global::Gtk.Entry entrySastav;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label5;

		private global::Gtk.SpinButton spinbuttonCijena;

		private global::Gtk.Label label8;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label6;

		private global::Gtk.ComboBox comboboxOznaka;

		private global::Gtk.HBox hbox8;

		private global::Gtk.HBox hbox9;

		protected virtual void Build() {
			global::Stetic.Gui.Initialize(this);
			// Widget NewRestoran.ArtikliWindow
			this.Name = "NewRestoran.ArtikliWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Artikli");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.BorderWidth = ((uint)(13));
			// Container child NewRestoran.ArtikliWindow.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeviewArtikli = new global::Gtk.NodeView();
			this.nodeviewArtikli.CanFocus = true;
			this.nodeviewArtikli.Name = "nodeviewArtikli";
			this.nodeviewArtikli.Reorderable = true;
			this.nodeviewArtikli.RulesHint = true;
			this.nodeviewArtikli.SearchColumn = 0;
			this.GtkScrolledWindow.Add(this.nodeviewArtikli);
			this.hbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.WidthRequest = 100;
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Šifra:");
			this.hbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(25));
			// Container child hbox1.Gtk.Box+BoxChild
			this.entrySifra = new global::Gtk.Entry();
			this.entrySifra.WidthRequest = 290;
			this.entrySifra.CanFocus = true;
			this.entrySifra.Name = "entrySifra";
			this.entrySifra.IsEditable = true;
			this.entrySifra.InvisibleChar = '●';
			this.hbox1.Add(this.entrySifra);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entrySifra]));
			w4.Position = 1;
			w4.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.WidthRequest = 18;
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add(this.vseparator1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vseparator1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.WidthRequest = 100;
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.hbox1.Add(this.entry3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entry3]));
			w6.Position = 3;
			w6.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSearch = new global::Gtk.Button();
			this.buttonSearch.WidthRequest = 39;
			this.buttonSearch.HeightRequest = 25;
			this.buttonSearch.CanFocus = true;
			this.buttonSearch.Name = "buttonSearch";
			this.buttonSearch.UseUnderline = true;
			global::Gtk.Image w7 = new global::Gtk.Image();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-find", global::Gtk.IconSize.SmallToolbar);
			this.buttonSearch.Image = w7;
			this.hbox1.Add(this.buttonSearch);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonSearch]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.WidthRequest = 100;
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Naziv:");
			this.hbox3.Add(this.label2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label2]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(25));
			// Container child hbox3.Gtk.Box+BoxChild
			this.entryNaziv = new global::Gtk.Entry();
			this.entryNaziv.WidthRequest = 290;
			this.entryNaziv.CanFocus = true;
			this.entryNaziv.Name = "entryNaziv";
			this.entryNaziv.IsEditable = true;
			this.entryNaziv.InvisibleChar = '●';
			this.hbox3.Add(this.entryNaziv);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entryNaziv]));
			w11.Position = 1;
			w11.Expand = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 100;
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Duži naziv:");
			this.hbox4.Add(this.label3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label3]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(25));
			// Container child hbox4.Gtk.Box+BoxChild
			this.entryDuziNaziv = new global::Gtk.Entry();
			this.entryDuziNaziv.WidthRequest = 290;
			this.entryDuziNaziv.CanFocus = true;
			this.entryDuziNaziv.Name = "entryDuziNaziv";
			this.entryDuziNaziv.IsEditable = true;
			this.entryDuziNaziv.InvisibleChar = '●';
			this.hbox4.Add(this.entryDuziNaziv);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.entryDuziNaziv]));
			w14.Position = 1;
			w14.Expand = false;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.WidthRequest = 100;
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Sastav:");
			this.hbox5.Add(this.label4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label4]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			w16.Padding = ((uint)(25));
			// Container child hbox5.Gtk.Box+BoxChild
			this.entrySastav = new global::Gtk.Entry();
			this.entrySastav.WidthRequest = 290;
			this.entrySastav.CanFocus = true;
			this.entrySastav.Name = "entrySastav";
			this.entrySastav.IsEditable = true;
			this.entrySastav.InvisibleChar = '●';
			this.hbox5.Add(this.entrySastav);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entrySastav]));
			w17.Position = 1;
			w17.Expand = false;
			this.vbox1.Add(this.hbox5);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.WidthRequest = 100;
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("CIjena:");
			this.hbox6.Add(this.label5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label5]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(25));
			// Container child hbox6.Gtk.Box+BoxChild
			this.spinbuttonCijena = new global::Gtk.SpinButton(0D, 1000D, 1D);
			this.spinbuttonCijena.WidthRequest = 290;
			this.spinbuttonCijena.CanFocus = true;
			this.spinbuttonCijena.Name = "spinbuttonCijena";
			this.spinbuttonCijena.Adjustment.PageIncrement = 10D;
			this.spinbuttonCijena.ClimbRate = 1D;
			this.spinbuttonCijena.Digits = ((uint)(2));
			this.spinbuttonCijena.Numeric = true;
			this.hbox6.Add(this.spinbuttonCijena);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.spinbuttonCijena]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("kn");
			this.hbox6.Add(this.label8);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label8]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox1.Add(this.hbox6);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
			w22.Position = 4;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.WidthRequest = 100;
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Oznaka:");
			this.hbox7.Add(this.label6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label6]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			w23.Padding = ((uint)(25));
			// Container child hbox7.Gtk.Box+BoxChild
			this.comboboxOznaka = new global::Gtk.ComboBox();
			this.comboboxOznaka.WidthRequest = 290;
			this.comboboxOznaka.Name = "comboboxOznaka";
			this.hbox7.Add(this.comboboxOznaka);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.comboboxOznaka]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox1.Add(this.hbox7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox7]));
			w25.Position = 5;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			this.vbox1.Add(this.hbox8);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox8]));
			w26.Position = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			this.vbox1.Add(this.hbox9);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox9]));
			w27.Position = 7;
			this.hbox2.Add(this.vbox1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox1]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.Add(this.hbox2);
			if((this.Child != null)) {
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1165;
			this.DefaultHeight = 362;
			this.Show();
			this.buttonSearch.Clicked += new global::System.EventHandler(this.OnButtonSearchClicked);
		}
	}
}
