
// This file has been generated by the GUI designer. Do not modify.
namespace NewRestoran
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action OdjavaAction;

		private global::Gtk.Action PoetnaAction;

		private global::Gtk.Action RefreshAction;

		private global::Gtk.Action PodaciAction;

		private global::Gtk.Action ArtikliAction;

		private global::Gtk.Action StoloviAction;

		private global::Gtk.Action ZaposleniciAction;

		private global::Gtk.Action ZaliheAction;

		private global::Gtk.Action StatistikaAction;

		private global::Gtk.Action quitAction;

		private global::Gtk.Action homeAction;

		private global::Gtk.ToggleAction windowAction;

		private global::Gtk.Action PodaciAction1;

		private global::Gtk.Action ArtikliAction1;

		private global::Gtk.Action StoloviAction1;

		private global::Gtk.Action ZaposleniciAction1;

		private global::Gtk.Action ZalihaAction;

		private global::Gtk.Action StatistikaAction1;

		private global::Gtk.Action QuitAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.Notebook notebookMain;

		private global::Gtk.HBox hbox1;

		private global::NewRestoran.FixedRestoranSheme fixedrestoransheme;

		private global::Gtk.VBox vboxNodeViewPrikaz;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Button buttonSearch;

		private global::Gtk.Entry entrySearch;

		private global::Gtk.Label label13;

		private global::Gtk.ScrolledWindow GtkScrolledWindowNarudzbe;

		private global::Gtk.NodeView nodeviewNarudzbe;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Label label15;

		private global::Gtk.Label label14;

		private global::Gtk.HBox hbox7;

		private global::Gtk.ComboBox comboboxSveTrenutna;

		private global::Gtk.ComboBox comboboxStatus;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.ScrolledWindow GtkScrolledWindowStatusStavaka;

		private global::Gtk.NodeView nodeviewNarudzbeStatus;

		private global::Gtk.VBox vboxFormPrikaz;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label6;

		private global::Gtk.Label labelBroj;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label label8;

		private global::Gtk.Label labelDatum;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label7;

		private global::Gtk.ComboBox comboboxOznakaStola;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Label label9;

		private global::Gtk.Label labelUkupno;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Button buttonOdustani;

		private global::Gtk.Button buttonSpremi;

		private global::Gtk.HBox hboxSpremljen;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Image image251;

		private global::Gtk.Label labelSpremljen;

		private global::Gtk.VBox vboxNarudzbeButtons;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Button buttonDodaj;

		private global::Gtk.Button buttonStavke;

		private global::Gtk.Button buttonNarudzbeUp;

		private global::Gtk.Button buttonNarudzbeDown;

		private global::Gtk.Button buttonNarudzbeChange;

		private global::Gtk.Button buttonDeleteNarudzba;

		private global::Gtk.Button buttonZakljuci;

		private global::Gtk.VBox vboxStatusButtons;

		private global::Gtk.Button buttonDeliver;

		private global::Gtk.Button buttonStatusDown;

		private global::Gtk.Button buttonStatusUp;

		private global::Gtk.Button buttonFinishOrder;

		private global::Gtk.Button buttonTakeOrder;

		private global::Gtk.Label label2;

		private global::Gtk.HBox boxStavke;

		private global::Gtk.Label label5;

		private global::Gtk.HBox boxArtikli;

		private global::Gtk.Label label10;

		private global::Gtk.HBox boxZaposlenici;

		private global::Gtk.Label label11;

		private global::Gtk.HBox boxStolovi;

		private global::Gtk.Label label12;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NewRestoran.MainWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.OdjavaAction = new global::Gtk.Action("OdjavaAction", global::Mono.Unix.Catalog.GetString("Odjava"), null, "lock");
			this.OdjavaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Odjava");
			w1.Add(this.OdjavaAction, null);
			this.PoetnaAction = new global::Gtk.Action("PoetnaAction", global::Mono.Unix.Catalog.GetString("Početna"), null, "table2chairs");
			this.PoetnaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Početna");
			w1.Add(this.PoetnaAction, null);
			this.RefreshAction = new global::Gtk.Action("RefreshAction", global::Mono.Unix.Catalog.GetString("Refresh"), null, "table4chairs");
			this.RefreshAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Refresh");
			w1.Add(this.RefreshAction, null);
			this.PodaciAction = new global::Gtk.Action("PodaciAction", global::Mono.Unix.Catalog.GetString("Podaci"), null, null);
			this.PodaciAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Podaci");
			w1.Add(this.PodaciAction, null);
			this.ArtikliAction = new global::Gtk.Action("ArtikliAction", global::Mono.Unix.Catalog.GetString("Artikli"), null, null);
			this.ArtikliAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Artikli");
			w1.Add(this.ArtikliAction, null);
			this.StoloviAction = new global::Gtk.Action("StoloviAction", global::Mono.Unix.Catalog.GetString("Stolovi"), null, null);
			this.StoloviAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Stolovi");
			w1.Add(this.StoloviAction, null);
			this.ZaposleniciAction = new global::Gtk.Action("ZaposleniciAction", global::Mono.Unix.Catalog.GetString("Zaposlenici"), null, null);
			this.ZaposleniciAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Zaposlenici");
			w1.Add(this.ZaposleniciAction, null);
			this.ZaliheAction = new global::Gtk.Action("ZaliheAction", global::Mono.Unix.Catalog.GetString("Zalihe"), null, null);
			this.ZaliheAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Zalihe");
			w1.Add(this.ZaliheAction, null);
			this.StatistikaAction = new global::Gtk.Action("StatistikaAction", global::Mono.Unix.Catalog.GetString("Statistika"), null, null);
			this.StatistikaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Statistika");
			w1.Add(this.StatistikaAction, null);
			this.quitAction = new global::Gtk.Action("quitAction", global::Mono.Unix.Catalog.GetString("Odjava"), null, "gtk-quit");
			this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Odjava");
			w1.Add(this.quitAction, null);
			this.homeAction = new global::Gtk.Action("homeAction", global::Mono.Unix.Catalog.GetString("Početna"), null, "gtk-home");
			this.homeAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Početna");
			w1.Add(this.homeAction, null);
			this.windowAction = new global::Gtk.ToggleAction("windowAction", global::Mono.Unix.Catalog.GetString("Window"), null, "gtk-fullscreen");
			this.windowAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Window");
			w1.Add(this.windowAction, null);
			this.PodaciAction1 = new global::Gtk.Action("PodaciAction1", global::Mono.Unix.Catalog.GetString("Podaci"), null, null);
			this.PodaciAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Podaci");
			w1.Add(this.PodaciAction1, null);
			this.ArtikliAction1 = new global::Gtk.Action("ArtikliAction1", global::Mono.Unix.Catalog.GetString("Artikli"), null, null);
			this.ArtikliAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Artikli");
			w1.Add(this.ArtikliAction1, null);
			this.StoloviAction1 = new global::Gtk.Action("StoloviAction1", global::Mono.Unix.Catalog.GetString("Stolovi"), null, null);
			this.StoloviAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Stolovi");
			w1.Add(this.StoloviAction1, null);
			this.ZaposleniciAction1 = new global::Gtk.Action("ZaposleniciAction1", global::Mono.Unix.Catalog.GetString("Zaposlenici"), null, null);
			this.ZaposleniciAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Zaposlenici");
			w1.Add(this.ZaposleniciAction1, null);
			this.ZalihaAction = new global::Gtk.Action("ZalihaAction", global::Mono.Unix.Catalog.GetString("Zaliha"), null, null);
			this.ZalihaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Zaliha");
			w1.Add(this.ZalihaAction, null);
			this.StatistikaAction1 = new global::Gtk.Action("StatistikaAction1", global::Mono.Unix.Catalog.GetString("Statistika"), null, null);
			this.StatistikaAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Statisika");
			w1.Add(this.StatistikaAction1, null);
			this.QuitAction = new global::Gtk.Action("QuitAction", global::Mono.Unix.Catalog.GetString("Quit"), null, "shoutdown");
			this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Quit");
			w1.Add(this.QuitAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "NewRestoran.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("NewRestoran");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.logo.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child NewRestoran.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='PodaciAction1' action='PodaciAction1'><menuitem name='ArtikliAction1' action='ArtikliAction1'/><menuitem name='StoloviAction1' action='StoloviAction1'/><menuitem name='ZaposleniciAction1' action='ZaposleniciAction1'/></menu><menuitem name='ZalihaAction' action='ZalihaAction'/><menuitem name='StatistikaAction1' action='StatistikaAction1'/></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add(this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar1\'><toolitem name=\'QuitAction\' action=\'QuitAction\'/><to" +
					"olitem name=\'quitAction\' action=\'quitAction\'/><toolitem name=\'homeAction\' action" +
					"=\'homeAction\'/><toolitem name=\'windowAction\' action=\'windowAction\'/></toolbar></" +
					"ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.vbox1.Add(this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w4 = new global::Gtk.Viewport();
			w4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.notebookMain = new global::Gtk.Notebook();
			this.notebookMain.CanFocus = true;
			this.notebookMain.Name = "notebookMain";
			this.notebookMain.CurrentPage = 0;
			this.notebookMain.EnablePopup = true;
			this.notebookMain.Scrollable = true;
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixedrestoransheme = new global::NewRestoran.FixedRestoranSheme();
			this.fixedrestoransheme.Events = ((global::Gdk.EventMask)(256));
			this.fixedrestoransheme.Name = "fixedrestoransheme";
			this.fixedrestoransheme.ToolboxShown = false;
			this.hbox1.Add(this.fixedrestoransheme);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixedrestoransheme]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vboxNodeViewPrikaz = new global::Gtk.VBox();
			this.vboxNodeViewPrikaz.Name = "vboxNodeViewPrikaz";
			this.vboxNodeViewPrikaz.Spacing = 6;
			// Container child vboxNodeViewPrikaz.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonSearch = new global::Gtk.Button();
			this.buttonSearch.WidthRequest = 39;
			this.buttonSearch.HeightRequest = 25;
			this.buttonSearch.CanFocus = true;
			this.buttonSearch.Name = "buttonSearch";
			this.buttonSearch.UseUnderline = true;
			global::Gtk.Image w6 = new global::Gtk.Image();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-find", global::Gtk.IconSize.Menu);
			this.buttonSearch.Image = w6;
			this.hbox6.Add(this.buttonSearch);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.buttonSearch]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entrySearch = new global::Gtk.Entry();
			this.entrySearch.WidthRequest = 130;
			this.entrySearch.CanFocus = true;
			this.entrySearch.Name = "entrySearch";
			this.entrySearch.IsEditable = true;
			this.entrySearch.InvisibleChar = '●';
			this.hbox6.Add(this.entrySearch);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entrySearch]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 1;
			w8.Expand = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Filtriraj narudžbe: ");
			this.hbox6.Add(this.label13);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label13]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vboxNodeViewPrikaz.Add(this.hbox6);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxNodeViewPrikaz[this.hbox6]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vboxNodeViewPrikaz.Gtk.Box+BoxChild
			this.GtkScrolledWindowNarudzbe = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindowNarudzbe.HeightRequest = 300;
			this.GtkScrolledWindowNarudzbe.Name = "GtkScrolledWindowNarudzbe";
			this.GtkScrolledWindowNarudzbe.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindowNarudzbe.Gtk.Container+ContainerChild
			this.nodeviewNarudzbe = new global::Gtk.NodeView();
			this.nodeviewNarudzbe.WidthRequest = 600;
			this.nodeviewNarudzbe.CanFocus = true;
			this.nodeviewNarudzbe.Name = "nodeviewNarudzbe";
			this.nodeviewNarudzbe.Reorderable = true;
			this.nodeviewNarudzbe.RulesHint = true;
			this.nodeviewNarudzbe.SearchColumn = 0;
			this.GtkScrolledWindowNarudzbe.Add(this.nodeviewNarudzbe);
			this.vboxNodeViewPrikaz.Add(this.GtkScrolledWindowNarudzbe);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxNodeViewPrikaz[this.GtkScrolledWindowNarudzbe]));
			w12.Position = 1;
			w12.Expand = false;
			// Container child vboxNodeViewPrikaz.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.HeightRequest = 12;
			this.hseparator1.Name = "hseparator1";
			this.vboxNodeViewPrikaz.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxNodeViewPrikaz[this.hseparator1]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vboxNodeViewPrikaz.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Prikaz stavaka trenutne ili svih narudžba:");
			this.hbox13.Add(this.label15);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label15]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.WidthRequest = 180;
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Prikaz stavaka prema statusu:");
			this.hbox13.Add(this.label14);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label14]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vboxNodeViewPrikaz.Add(this.hbox13);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vboxNodeViewPrikaz[this.hbox13]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vboxNodeViewPrikaz.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.comboboxSveTrenutna = new global::Gtk.ComboBox();
			this.comboboxSveTrenutna.WidthRequest = 180;
			this.comboboxSveTrenutna.Name = "comboboxSveTrenutna";
			this.hbox7.Add(this.comboboxSveTrenutna);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.comboboxSveTrenutna]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.comboboxStatus = new global::Gtk.ComboBox();
			this.comboboxStatus.WidthRequest = 180;
			this.comboboxStatus.Name = "comboboxStatus";
			this.hbox7.Add(this.comboboxStatus);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.comboboxStatus]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vboxNodeViewPrikaz.Add(this.hbox7);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vboxNodeViewPrikaz[this.hbox7]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vboxNodeViewPrikaz.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.HeightRequest = 12;
			this.hseparator2.Name = "hseparator2";
			this.vboxNodeViewPrikaz.Add(this.hseparator2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vboxNodeViewPrikaz[this.hseparator2]));
			w20.Position = 5;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vboxNodeViewPrikaz.Gtk.Box+BoxChild
			this.GtkScrolledWindowStatusStavaka = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindowStatusStavaka.HeightRequest = 300;
			this.GtkScrolledWindowStatusStavaka.Name = "GtkScrolledWindowStatusStavaka";
			this.GtkScrolledWindowStatusStavaka.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindowStatusStavaka.Gtk.Container+ContainerChild
			this.nodeviewNarudzbeStatus = new global::Gtk.NodeView();
			this.nodeviewNarudzbeStatus.WidthRequest = 600;
			this.nodeviewNarudzbeStatus.CanFocus = true;
			this.nodeviewNarudzbeStatus.Name = "nodeviewNarudzbeStatus";
			this.nodeviewNarudzbeStatus.Reorderable = true;
			this.nodeviewNarudzbeStatus.RulesHint = true;
			this.nodeviewNarudzbeStatus.SearchColumn = 0;
			this.GtkScrolledWindowStatusStavaka.Add(this.nodeviewNarudzbeStatus);
			this.vboxNodeViewPrikaz.Add(this.GtkScrolledWindowStatusStavaka);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vboxNodeViewPrikaz[this.GtkScrolledWindowStatusStavaka]));
			w22.Position = 6;
			w22.Expand = false;
			this.hbox1.Add(this.vboxNodeViewPrikaz);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vboxNodeViewPrikaz]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vboxFormPrikaz = new global::Gtk.VBox();
			this.vboxFormPrikaz.Name = "vboxFormPrikaz";
			this.vboxFormPrikaz.Spacing = 24;
			this.vboxFormPrikaz.BorderWidth = ((uint)(60));
			// Container child vboxFormPrikaz.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.WidthRequest = 110;
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Broj:");
			this.hbox8.Add(this.label6);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label6]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			w24.Padding = ((uint)(15));
			// Container child hbox8.Gtk.Box+BoxChild
			this.labelBroj = new global::Gtk.Label();
			this.labelBroj.WidthRequest = 140;
			this.labelBroj.Name = "labelBroj";
			this.labelBroj.Xalign = 0F;
			this.hbox8.Add(this.labelBroj);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.labelBroj]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.vboxFormPrikaz.Add(this.hbox8);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vboxFormPrikaz[this.hbox8]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vboxFormPrikaz.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.WidthRequest = 110;
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Datum:");
			this.hbox9.Add(this.label8);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label8]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			w27.Padding = ((uint)(15));
			// Container child hbox9.Gtk.Box+BoxChild
			this.labelDatum = new global::Gtk.Label();
			this.labelDatum.WidthRequest = 140;
			this.labelDatum.Name = "labelDatum";
			this.hbox9.Add(this.labelDatum);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.labelDatum]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.vboxFormPrikaz.Add(this.hbox9);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vboxFormPrikaz[this.hbox9]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vboxFormPrikaz.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.WidthRequest = 110;
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Oznaka stola:");
			this.hbox10.Add(this.label7);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label7]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			w30.Padding = ((uint)(15));
			// Container child hbox10.Gtk.Box+BoxChild
			this.comboboxOznakaStola = new global::Gtk.ComboBox();
			this.comboboxOznakaStola.WidthRequest = 140;
			this.comboboxOznakaStola.Name = "comboboxOznakaStola";
			this.hbox10.Add(this.comboboxOznakaStola);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.comboboxOznakaStola]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.vboxFormPrikaz.Add(this.hbox10);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vboxFormPrikaz[this.hbox10]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vboxFormPrikaz.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.WidthRequest = 110;
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Ukupno:");
			this.hbox11.Add(this.label9);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.label9]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			w33.Padding = ((uint)(15));
			// Container child hbox11.Gtk.Box+BoxChild
			this.labelUkupno = new global::Gtk.Label();
			this.labelUkupno.Name = "labelUkupno";
			this.hbox11.Add(this.labelUkupno);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.labelUkupno]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			this.vboxFormPrikaz.Add(this.hbox11);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vboxFormPrikaz[this.hbox11]));
			w35.Position = 3;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vboxFormPrikaz.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 20;
			this.hbox12.BorderWidth = ((uint)(25));
			// Container child hbox12.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.WidthRequest = 27;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox12.Add(this.fixed2);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.fixed2]));
			w36.Position = 0;
			w36.Expand = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.buttonOdustani = new global::Gtk.Button();
			this.buttonOdustani.WidthRequest = 150;
			this.buttonOdustani.HeightRequest = 50;
			this.buttonOdustani.CanFocus = true;
			this.buttonOdustani.Name = "buttonOdustani";
			this.buttonOdustani.UseUnderline = true;
			this.buttonOdustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			global::Gtk.Image w37 = new global::Gtk.Image();
			w37.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Button);
			this.buttonOdustani.Image = w37;
			this.hbox12.Add(this.buttonOdustani);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.buttonOdustani]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.buttonSpremi = new global::Gtk.Button();
			this.buttonSpremi.WidthRequest = 150;
			this.buttonSpremi.HeightRequest = 50;
			this.buttonSpremi.CanFocus = true;
			this.buttonSpremi.Name = "buttonSpremi";
			this.buttonSpremi.UseUnderline = true;
			this.buttonSpremi.Label = global::Mono.Unix.Catalog.GetString("Spremi");
			global::Gtk.Image w39 = new global::Gtk.Image();
			w39.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Button);
			this.buttonSpremi.Image = w39;
			this.hbox12.Add(this.buttonSpremi);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.buttonSpremi]));
			w40.Position = 2;
			w40.Expand = false;
			w40.Fill = false;
			this.vboxFormPrikaz.Add(this.hbox12);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vboxFormPrikaz[this.hbox12]));
			w41.Position = 4;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vboxFormPrikaz.Gtk.Box+BoxChild
			this.hboxSpremljen = new global::Gtk.HBox();
			this.hboxSpremljen.WidthRequest = 0;
			this.hboxSpremljen.Name = "hboxSpremljen";
			this.hboxSpremljen.Spacing = 6;
			this.hboxSpremljen.BorderWidth = ((uint)(17));
			// Container child hboxSpremljen.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.WidthRequest = 145;
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.hboxSpremljen.Add(this.fixed4);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hboxSpremljen[this.fixed4]));
			w42.Position = 0;
			w42.Expand = false;
			// Container child hboxSpremljen.Gtk.Box+BoxChild
			this.image251 = new global::Gtk.Image();
			this.image251.Name = "image251";
			this.image251.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "Dostavljeno", global::Gtk.IconSize.Dnd);
			this.hboxSpremljen.Add(this.image251);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hboxSpremljen[this.image251]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			// Container child hboxSpremljen.Gtk.Box+BoxChild
			this.labelSpremljen = new global::Gtk.Label();
			this.labelSpremljen.Name = "labelSpremljen";
			this.labelSpremljen.LabelProp = global::Mono.Unix.Catalog.GetString("Spremljeno");
			this.hboxSpremljen.Add(this.labelSpremljen);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hboxSpremljen[this.labelSpremljen]));
			w44.Position = 2;
			w44.Expand = false;
			w44.Fill = false;
			this.vboxFormPrikaz.Add(this.hboxSpremljen);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vboxFormPrikaz[this.hboxSpremljen]));
			w45.Position = 5;
			w45.Expand = false;
			w45.Fill = false;
			this.hbox1.Add(this.vboxFormPrikaz);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vboxFormPrikaz]));
			w46.Position = 2;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vboxNarudzbeButtons = new global::Gtk.VBox();
			this.vboxNarudzbeButtons.Name = "vboxNarudzbeButtons";
			this.vboxNarudzbeButtons.Spacing = 23;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.HeightRequest = 7;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vboxNarudzbeButtons.Add(this.fixed1);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.fixed1]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonDodaj = new global::Gtk.Button();
			this.buttonDodaj.CanFocus = true;
			this.buttonDodaj.Name = "buttonDodaj";
			this.buttonDodaj.UseUnderline = true;
			this.buttonDodaj.FocusOnClick = false;
			global::Gtk.Image w48 = new global::Gtk.Image();
			w48.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.add-order.png");
			this.buttonDodaj.Image = w48;
			this.vboxNarudzbeButtons.Add(this.buttonDodaj);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonDodaj]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonStavke = new global::Gtk.Button();
			this.buttonStavke.CanFocus = true;
			this.buttonStavke.Name = "buttonStavke";
			this.buttonStavke.UseUnderline = true;
			this.buttonStavke.FocusOnClick = false;
			global::Gtk.Image w50 = new global::Gtk.Image();
			w50.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.add-item.png");
			this.buttonStavke.Image = w50;
			this.vboxNarudzbeButtons.Add(this.buttonStavke);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonStavke]));
			w51.Position = 2;
			w51.Expand = false;
			w51.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonNarudzbeUp = new global::Gtk.Button();
			this.buttonNarudzbeUp.CanFocus = true;
			this.buttonNarudzbeUp.Name = "buttonNarudzbeUp";
			this.buttonNarudzbeUp.UseUnderline = true;
			this.buttonNarudzbeUp.FocusOnClick = false;
			global::Gtk.Image w52 = new global::Gtk.Image();
			w52.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.up.png");
			this.buttonNarudzbeUp.Image = w52;
			this.vboxNarudzbeButtons.Add(this.buttonNarudzbeUp);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonNarudzbeUp]));
			w53.Position = 3;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonNarudzbeDown = new global::Gtk.Button();
			this.buttonNarudzbeDown.CanFocus = true;
			this.buttonNarudzbeDown.Name = "buttonNarudzbeDown";
			this.buttonNarudzbeDown.UseUnderline = true;
			this.buttonNarudzbeDown.FocusOnClick = false;
			global::Gtk.Image w54 = new global::Gtk.Image();
			w54.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.down.png");
			this.buttonNarudzbeDown.Image = w54;
			this.vboxNarudzbeButtons.Add(this.buttonNarudzbeDown);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonNarudzbeDown]));
			w55.Position = 4;
			w55.Expand = false;
			w55.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonNarudzbeChange = new global::Gtk.Button();
			this.buttonNarudzbeChange.CanFocus = true;
			this.buttonNarudzbeChange.Name = "buttonNarudzbeChange";
			this.buttonNarudzbeChange.UseUnderline = true;
			this.buttonNarudzbeChange.FocusOnClick = false;
			global::Gtk.Image w56 = new global::Gtk.Image();
			w56.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.change.png");
			this.buttonNarudzbeChange.Image = w56;
			this.vboxNarudzbeButtons.Add(this.buttonNarudzbeChange);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonNarudzbeChange]));
			w57.Position = 5;
			w57.Expand = false;
			w57.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonDeleteNarudzba = new global::Gtk.Button();
			this.buttonDeleteNarudzba.CanFocus = true;
			this.buttonDeleteNarudzba.Name = "buttonDeleteNarudzba";
			this.buttonDeleteNarudzba.UseUnderline = true;
			this.buttonDeleteNarudzba.FocusOnClick = false;
			global::Gtk.Image w58 = new global::Gtk.Image();
			w58.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.delete.png");
			this.buttonDeleteNarudzba.Image = w58;
			this.vboxNarudzbeButtons.Add(this.buttonDeleteNarudzba);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonDeleteNarudzba]));
			w59.Position = 6;
			w59.Expand = false;
			w59.Fill = false;
			// Container child vboxNarudzbeButtons.Gtk.Box+BoxChild
			this.buttonZakljuci = new global::Gtk.Button();
			this.buttonZakljuci.CanFocus = true;
			this.buttonZakljuci.Name = "buttonZakljuci";
			this.buttonZakljuci.UseUnderline = true;
			this.buttonZakljuci.FocusOnClick = false;
			global::Gtk.Image w60 = new global::Gtk.Image();
			w60.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.lock.png");
			this.buttonZakljuci.Image = w60;
			this.vboxNarudzbeButtons.Add(this.buttonZakljuci);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vboxNarudzbeButtons[this.buttonZakljuci]));
			w61.Position = 7;
			w61.Expand = false;
			w61.Fill = false;
			this.hbox1.Add(this.vboxNarudzbeButtons);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vboxNarudzbeButtons]));
			w62.Position = 3;
			w62.Expand = false;
			w62.Fill = false;
			w62.Padding = ((uint)(32));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vboxStatusButtons = new global::Gtk.VBox();
			this.vboxStatusButtons.Name = "vboxStatusButtons";
			this.vboxStatusButtons.Spacing = 23;
			// Container child vboxStatusButtons.Gtk.Box+BoxChild
			this.buttonDeliver = new global::Gtk.Button();
			this.buttonDeliver.CanFocus = true;
			this.buttonDeliver.Name = "buttonDeliver";
			this.buttonDeliver.UseUnderline = true;
			this.buttonDeliver.FocusOnClick = false;
			global::Gtk.Image w63 = new global::Gtk.Image();
			w63.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.delivering.png");
			this.buttonDeliver.Image = w63;
			this.vboxStatusButtons.Add(this.buttonDeliver);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.vboxStatusButtons[this.buttonDeliver]));
			w64.PackType = ((global::Gtk.PackType)(1));
			w64.Position = 0;
			w64.Expand = false;
			w64.Fill = false;
			// Container child vboxStatusButtons.Gtk.Box+BoxChild
			this.buttonStatusDown = new global::Gtk.Button();
			this.buttonStatusDown.CanFocus = true;
			this.buttonStatusDown.Name = "buttonStatusDown";
			this.buttonStatusDown.UseUnderline = true;
			this.buttonStatusDown.FocusOnClick = false;
			global::Gtk.Image w65 = new global::Gtk.Image();
			w65.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.down.png");
			this.buttonStatusDown.Image = w65;
			this.vboxStatusButtons.Add(this.buttonStatusDown);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vboxStatusButtons[this.buttonStatusDown]));
			w66.PackType = ((global::Gtk.PackType)(1));
			w66.Position = 1;
			w66.Expand = false;
			w66.Fill = false;
			// Container child vboxStatusButtons.Gtk.Box+BoxChild
			this.buttonStatusUp = new global::Gtk.Button();
			this.buttonStatusUp.CanFocus = true;
			this.buttonStatusUp.Name = "buttonStatusUp";
			this.buttonStatusUp.UseUnderline = true;
			this.buttonStatusUp.FocusOnClick = false;
			global::Gtk.Image w67 = new global::Gtk.Image();
			w67.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.up.png");
			this.buttonStatusUp.Image = w67;
			this.vboxStatusButtons.Add(this.buttonStatusUp);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vboxStatusButtons[this.buttonStatusUp]));
			w68.PackType = ((global::Gtk.PackType)(1));
			w68.Position = 2;
			w68.Expand = false;
			w68.Fill = false;
			// Container child vboxStatusButtons.Gtk.Box+BoxChild
			this.buttonFinishOrder = new global::Gtk.Button();
			this.buttonFinishOrder.CanFocus = true;
			this.buttonFinishOrder.Name = "buttonFinishOrder";
			this.buttonFinishOrder.UseUnderline = true;
			this.buttonFinishOrder.FocusOnClick = false;
			global::Gtk.Image w69 = new global::Gtk.Image();
			w69.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.order-ready.png");
			this.buttonFinishOrder.Image = w69;
			this.vboxStatusButtons.Add(this.buttonFinishOrder);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vboxStatusButtons[this.buttonFinishOrder]));
			w70.PackType = ((global::Gtk.PackType)(1));
			w70.Position = 3;
			w70.Expand = false;
			w70.Fill = false;
			// Container child vboxStatusButtons.Gtk.Box+BoxChild
			this.buttonTakeOrder = new global::Gtk.Button();
			this.buttonTakeOrder.CanFocus = true;
			this.buttonTakeOrder.Name = "buttonTakeOrder";
			this.buttonTakeOrder.UseUnderline = true;
			this.buttonTakeOrder.FocusOnClick = false;
			global::Gtk.Image w71 = new global::Gtk.Image();
			w71.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.take-order.png");
			this.buttonTakeOrder.Image = w71;
			this.vboxStatusButtons.Add(this.buttonTakeOrder);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vboxStatusButtons[this.buttonTakeOrder]));
			w72.PackType = ((global::Gtk.PackType)(1));
			w72.Position = 4;
			w72.Expand = false;
			w72.Fill = false;
			this.hbox1.Add(this.vboxStatusButtons);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vboxStatusButtons]));
			w73.Position = 4;
			w73.Expand = false;
			w73.Fill = false;
			w73.Padding = ((uint)(32));
			this.notebookMain.Add(this.hbox1);
			// Notebook tab
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Main");
			this.notebookMain.SetTabLabel(this.hbox1, this.label2);
			this.label2.ShowAll();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.boxStavke = new global::Gtk.HBox();
			this.boxStavke.Name = "boxStavke";
			this.boxStavke.Spacing = 6;
			this.boxStavke.BorderWidth = ((uint)(20));
			this.notebookMain.Add(this.boxStavke);
			global::Gtk.Notebook.NotebookChild w75 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain[this.boxStavke]));
			w75.Position = 1;
			// Notebook tab
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Stavke");
			this.notebookMain.SetTabLabel(this.boxStavke, this.label5);
			this.label5.ShowAll();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.boxArtikli = new global::Gtk.HBox();
			this.boxArtikli.Name = "boxArtikli";
			this.boxArtikli.Spacing = 6;
			this.boxArtikli.BorderWidth = ((uint)(20));
			this.notebookMain.Add(this.boxArtikli);
			global::Gtk.Notebook.NotebookChild w76 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain[this.boxArtikli]));
			w76.Position = 2;
			// Notebook tab
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Artikli");
			this.notebookMain.SetTabLabel(this.boxArtikli, this.label10);
			this.label10.ShowAll();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.boxZaposlenici = new global::Gtk.HBox();
			this.boxZaposlenici.Name = "boxZaposlenici";
			this.boxZaposlenici.Spacing = 6;
			this.boxZaposlenici.BorderWidth = ((uint)(20));
			this.notebookMain.Add(this.boxZaposlenici);
			global::Gtk.Notebook.NotebookChild w77 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain[this.boxZaposlenici]));
			w77.Position = 3;
			// Notebook tab
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Zaposlenici");
			this.notebookMain.SetTabLabel(this.boxZaposlenici, this.label11);
			this.label11.ShowAll();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.boxStolovi = new global::Gtk.HBox();
			this.boxStolovi.Name = "boxStolovi";
			this.boxStolovi.Spacing = 6;
			this.boxStolovi.BorderWidth = ((uint)(20));
			this.notebookMain.Add(this.boxStolovi);
			global::Gtk.Notebook.NotebookChild w78 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain[this.boxStolovi]));
			w78.Position = 4;
			// Notebook tab
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Stolovi");
			this.notebookMain.SetTabLabel(this.boxStolovi, this.label12);
			this.label12.ShowAll();
			w4.Add(this.notebookMain);
			this.scrolledwindow1.Add(w4);
			this.vbox1.Add(this.scrolledwindow1);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow1]));
			w81.Position = 2;
			w81.Padding = ((uint)(10));
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 2161;
			this.DefaultHeight = 1104;
			this.hboxSpremljen.Hide();
			this.vboxFormPrikaz.Hide();
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.quitAction.Activated += new global::System.EventHandler(this.OnSingOutActionActivated);
			this.homeAction.Activated += new global::System.EventHandler(this.OnHomeActionActivated);
			this.ArtikliAction1.Activated += new global::System.EventHandler(this.OnArtikliActionActivated);
			this.StoloviAction1.Activated += new global::System.EventHandler(this.OnStoloviActionActivated);
			this.ZaposleniciAction1.Activated += new global::System.EventHandler(this.OnZaposleniciActionActivated);
			this.QuitAction.Activated += new global::System.EventHandler(this.OnQuitActionActivated);
			this.buttonSearch.Clicked += new global::System.EventHandler(this.OnButtonSearchClicked);
			this.comboboxSveTrenutna.Changed += new global::System.EventHandler(this.OnComboboxSveTrenutnaChanged);
			this.comboboxStatus.Changed += new global::System.EventHandler(this.OnComboboxStatusChanged);
			this.buttonOdustani.Clicked += new global::System.EventHandler(this.OnButtonOdustaniClicked);
			this.buttonSpremi.Clicked += new global::System.EventHandler(this.OnButtonSpremiClicked);
			this.buttonDodaj.Clicked += new global::System.EventHandler(this.OnButtonDodajClicked);
			this.buttonStavke.Clicked += new global::System.EventHandler(this.OnButtonStavkeClicked);
			this.buttonNarudzbeUp.Clicked += new global::System.EventHandler(this.OnButtonNarudzbeUpClicked);
			this.buttonNarudzbeDown.Clicked += new global::System.EventHandler(this.OnButtonNarudzbeDownClicked);
			this.buttonNarudzbeChange.Clicked += new global::System.EventHandler(this.OnButtonNarudzbeChangeClicked);
			this.buttonDeleteNarudzba.Clicked += new global::System.EventHandler(this.OnButtonDeleteNarudzbaClicked);
			this.buttonZakljuci.Clicked += new global::System.EventHandler(this.OnButtonZakljuciClicked);
			this.buttonTakeOrder.Clicked += new global::System.EventHandler(this.OnButtonUpdateStatusClicked);
			this.buttonFinishOrder.Clicked += new global::System.EventHandler(this.OnButtonUpdateStatusClicked);
			this.buttonStatusUp.Clicked += new global::System.EventHandler(this.OnButtonStatusUpClicked);
			this.buttonStatusDown.Clicked += new global::System.EventHandler(this.OnButtonStatusDownClicked);
			this.buttonDeliver.Clicked += new global::System.EventHandler(this.OnButtonUpdateStatusClicked);
		}
	}
}
