
// This file has been generated by the GUI designer. Do not modify.
namespace NewRestoran
{
	public partial class StoloviWindow
	{
		private global::Gtk.HBox hbox2;

		private global::Gtk.VBox vboxNodeView;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Button buttonSearch;

		private global::Gtk.Entry entrySearch;

		private global::Gtk.ScrolledWindow GtkScrolledWindowStolovi;

		private global::Gtk.NodeView nodeviewStolovi;

		private global::Gtk.VBox vboxFormView;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label1;

		private global::Gtk.Entry entryOznaka;

		private global::Gtk.VSeparator vseparator1;

		private global::Gtk.Entry entrySearchForm;

		private global::Gtk.Button buttonSearchForm;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label2;

		private global::Gtk.SpinButton spinbuttonBrojStolica;

		private global::Gtk.HBox hbox8;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Button buttonOdustani;

		private global::Gtk.Button buttonSpremi;

		private global::Gtk.HBox hbox9;

		private global::Gtk.HBox hboxSpremljeno;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Image image250;

		private global::Gtk.Label labelSpremljeno;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.Button buttonDodajStol;

		private global::Gtk.Button buttonUp;

		private global::Gtk.Button buttonDown;

		private global::Gtk.Button buttonChange;

		private global::Gtk.Button buttonDelete;

		private global::Gtk.Button buttonBackAndSave;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NewRestoran.StoloviWindow
			this.Name = "NewRestoran.StoloviWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Stolovi");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.logo.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.BorderWidth = ((uint)(15));
			// Container child NewRestoran.StoloviWindow.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vboxNodeView = new global::Gtk.VBox();
			this.vboxNodeView.Name = "vboxNodeView";
			this.vboxNodeView.Spacing = 6;
			// Container child vboxNodeView.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.buttonSearch = new global::Gtk.Button();
			this.buttonSearch.WidthRequest = 39;
			this.buttonSearch.HeightRequest = 25;
			this.buttonSearch.CanFocus = true;
			this.buttonSearch.Name = "buttonSearch";
			this.buttonSearch.UseUnderline = true;
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-find", global::Gtk.IconSize.SmallToolbar);
			this.buttonSearch.Image = w1;
			this.hbox10.Add(this.buttonSearch);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.buttonSearch]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.entrySearch = new global::Gtk.Entry();
			this.entrySearch.WidthRequest = 100;
			this.entrySearch.CanFocus = true;
			this.entrySearch.Name = "entrySearch";
			this.entrySearch.IsEditable = true;
			this.entrySearch.InvisibleChar = '●';
			this.hbox10.Add(this.entrySearch);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.entrySearch]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 1;
			w3.Expand = false;
			this.vboxNodeView.Add(this.hbox10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxNodeView[this.hbox10]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vboxNodeView.Gtk.Box+BoxChild
			this.GtkScrolledWindowStolovi = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindowStolovi.WidthRequest = 400;
			this.GtkScrolledWindowStolovi.HeightRequest = 550;
			this.GtkScrolledWindowStolovi.Name = "GtkScrolledWindowStolovi";
			this.GtkScrolledWindowStolovi.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindowStolovi.Gtk.Container+ContainerChild
			this.nodeviewStolovi = new global::Gtk.NodeView();
			this.nodeviewStolovi.WidthRequest = 400;
			this.nodeviewStolovi.CanFocus = true;
			this.nodeviewStolovi.Name = "nodeviewStolovi";
			this.nodeviewStolovi.Reorderable = true;
			this.nodeviewStolovi.RulesHint = true;
			this.nodeviewStolovi.SearchColumn = 0;
			this.GtkScrolledWindowStolovi.Add(this.nodeviewStolovi);
			this.vboxNodeView.Add(this.GtkScrolledWindowStolovi);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxNodeView[this.GtkScrolledWindowStolovi]));
			w6.Position = 1;
			w6.Expand = false;
			this.hbox2.Add(this.vboxNodeView);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vboxNodeView]));
			w7.Position = 0;
			w7.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vboxFormView = new global::Gtk.VBox();
			this.vboxFormView.Name = "vboxFormView";
			this.vboxFormView.Spacing = 16;
			this.vboxFormView.BorderWidth = ((uint)(31));
			// Container child vboxFormView.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.WidthRequest = 100;
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Oznaka:");
			this.hbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			w8.Padding = ((uint)(25));
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryOznaka = new global::Gtk.Entry();
			this.entryOznaka.WidthRequest = 290;
			this.entryOznaka.CanFocus = true;
			this.entryOznaka.Name = "entryOznaka";
			this.entryOznaka.IsEditable = true;
			this.entryOznaka.MaxLength = 20;
			this.entryOznaka.InvisibleChar = '●';
			this.hbox1.Add(this.entryOznaka);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entryOznaka]));
			w9.Position = 1;
			w9.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.WidthRequest = 18;
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add(this.vseparator1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vseparator1]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entrySearchForm = new global::Gtk.Entry();
			this.entrySearchForm.WidthRequest = 100;
			this.entrySearchForm.CanFocus = true;
			this.entrySearchForm.Name = "entrySearchForm";
			this.entrySearchForm.IsEditable = true;
			this.entrySearchForm.InvisibleChar = '●';
			this.hbox1.Add(this.entrySearchForm);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entrySearchForm]));
			w11.Position = 3;
			w11.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSearchForm = new global::Gtk.Button();
			this.buttonSearchForm.WidthRequest = 39;
			this.buttonSearchForm.HeightRequest = 25;
			this.buttonSearchForm.CanFocus = true;
			this.buttonSearchForm.Name = "buttonSearchForm";
			this.buttonSearchForm.UseUnderline = true;
			global::Gtk.Image w12 = new global::Gtk.Image();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-find", global::Gtk.IconSize.SmallToolbar);
			this.buttonSearchForm.Image = w12;
			this.hbox1.Add(this.buttonSearchForm);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonSearchForm]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			this.vboxFormView.Add(this.hbox1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxFormView[this.hbox1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vboxFormView.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.WidthRequest = 100;
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Broj stolica:");
			this.hbox3.Add(this.label2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label2]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			w15.Padding = ((uint)(25));
			// Container child hbox3.Gtk.Box+BoxChild
			this.spinbuttonBrojStolica = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.spinbuttonBrojStolica.WidthRequest = 290;
			this.spinbuttonBrojStolica.CanFocus = true;
			this.spinbuttonBrojStolica.Name = "spinbuttonBrojStolica";
			this.spinbuttonBrojStolica.Adjustment.PageIncrement = 10D;
			this.spinbuttonBrojStolica.ClimbRate = 1D;
			this.spinbuttonBrojStolica.Numeric = true;
			this.spinbuttonBrojStolica.SnapToTicks = true;
			this.hbox3.Add(this.spinbuttonBrojStolica);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.spinbuttonBrojStolica]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.vboxFormView.Add(this.hbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxFormView[this.hbox3]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vboxFormView.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 20;
			this.hbox12.BorderWidth = ((uint)(25));
			// Container child hbox12.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.WidthRequest = 98;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox12.Add(this.fixed2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.fixed2]));
			w18.Position = 0;
			w18.Expand = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.buttonOdustani = new global::Gtk.Button();
			this.buttonOdustani.WidthRequest = 150;
			this.buttonOdustani.HeightRequest = 50;
			this.buttonOdustani.CanFocus = true;
			this.buttonOdustani.Name = "buttonOdustani";
			this.buttonOdustani.UseUnderline = true;
			this.buttonOdustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			global::Gtk.Image w19 = new global::Gtk.Image();
			w19.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Button);
			this.buttonOdustani.Image = w19;
			this.hbox12.Add(this.buttonOdustani);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.buttonOdustani]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.buttonSpremi = new global::Gtk.Button();
			this.buttonSpremi.WidthRequest = 150;
			this.buttonSpremi.HeightRequest = 50;
			this.buttonSpremi.CanFocus = true;
			this.buttonSpremi.Name = "buttonSpremi";
			this.buttonSpremi.UseUnderline = true;
			this.buttonSpremi.Label = global::Mono.Unix.Catalog.GetString("Spremi");
			global::Gtk.Image w21 = new global::Gtk.Image();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Button);
			this.buttonSpremi.Image = w21;
			this.hbox12.Add(this.buttonSpremi);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.buttonSpremi]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.hbox8.Add(this.hbox12);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.hbox12]));
			w23.Position = 0;
			this.vboxFormView.Add(this.hbox8);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vboxFormView[this.hbox8]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vboxFormView.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hboxSpremljeno = new global::Gtk.HBox();
			this.hboxSpremljeno.WidthRequest = 0;
			this.hboxSpremljeno.Name = "hboxSpremljeno";
			this.hboxSpremljeno.Spacing = 6;
			this.hboxSpremljeno.BorderWidth = ((uint)(17));
			// Container child hboxSpremljeno.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.WidthRequest = 247;
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.hboxSpremljeno.Add(this.fixed4);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hboxSpremljeno[this.fixed4]));
			w25.Position = 0;
			w25.Expand = false;
			// Container child hboxSpremljeno.Gtk.Box+BoxChild
			this.image250 = new global::Gtk.Image();
			this.image250.Name = "image250";
			this.image250.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "Dostavljeno", global::Gtk.IconSize.Dnd);
			this.hboxSpremljeno.Add(this.image250);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hboxSpremljeno[this.image250]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hboxSpremljeno.Gtk.Box+BoxChild
			this.labelSpremljeno = new global::Gtk.Label();
			this.labelSpremljeno.Name = "labelSpremljeno";
			this.labelSpremljeno.LabelProp = global::Mono.Unix.Catalog.GetString("Spremljeno");
			this.hboxSpremljeno.Add(this.labelSpremljeno);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hboxSpremljeno[this.labelSpremljeno]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.hbox9.Add(this.hboxSpremljeno);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.hboxSpremljeno]));
			w28.Position = 0;
			this.vboxFormView.Add(this.hbox9);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vboxFormView[this.hbox9]));
			w29.Position = 3;
			w29.Expand = false;
			w29.Fill = false;
			this.hbox2.Add(this.vboxFormView);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vboxFormView]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 23;
			// Container child vbox2.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.WidthRequest = 0;
			this.fixed3.HeightRequest = 7;
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.vbox2.Add(this.fixed3);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.fixed3]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonDodajStol = new global::Gtk.Button();
			this.buttonDodajStol.CanFocus = true;
			this.buttonDodajStol.Name = "buttonDodajStol";
			this.buttonDodajStol.UseUnderline = true;
			this.buttonDodajStol.FocusOnClick = false;
			global::Gtk.Image w32 = new global::Gtk.Image();
			w32.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.add.png");
			this.buttonDodajStol.Image = w32;
			this.vbox2.Add(this.buttonDodajStol);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonDodajStol]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonUp = new global::Gtk.Button();
			this.buttonUp.CanFocus = true;
			this.buttonUp.Name = "buttonUp";
			this.buttonUp.UseUnderline = true;
			this.buttonUp.FocusOnClick = false;
			global::Gtk.Image w34 = new global::Gtk.Image();
			w34.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.up.png");
			this.buttonUp.Image = w34;
			this.vbox2.Add(this.buttonUp);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonUp]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonDown = new global::Gtk.Button();
			this.buttonDown.CanFocus = true;
			this.buttonDown.Name = "buttonDown";
			this.buttonDown.UseUnderline = true;
			this.buttonDown.FocusOnClick = false;
			global::Gtk.Image w36 = new global::Gtk.Image();
			w36.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.down.png");
			this.buttonDown.Image = w36;
			this.vbox2.Add(this.buttonDown);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonDown]));
			w37.Position = 3;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonChange = new global::Gtk.Button();
			this.buttonChange.CanFocus = true;
			this.buttonChange.Name = "buttonChange";
			this.buttonChange.UseUnderline = true;
			this.buttonChange.FocusOnClick = false;
			global::Gtk.Image w38 = new global::Gtk.Image();
			w38.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.change.png");
			this.buttonChange.Image = w38;
			this.vbox2.Add(this.buttonChange);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonChange]));
			w39.Position = 4;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonDelete = new global::Gtk.Button();
			this.buttonDelete.CanFocus = true;
			this.buttonDelete.Name = "buttonDelete";
			this.buttonDelete.UseUnderline = true;
			this.buttonDelete.FocusOnClick = false;
			global::Gtk.Image w40 = new global::Gtk.Image();
			w40.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.delete.png");
			this.buttonDelete.Image = w40;
			this.vbox2.Add(this.buttonDelete);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonDelete]));
			w41.Position = 5;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonBackAndSave = new global::Gtk.Button();
			this.buttonBackAndSave.CanFocus = true;
			this.buttonBackAndSave.Name = "buttonBackAndSave";
			this.buttonBackAndSave.UseUnderline = true;
			this.buttonBackAndSave.FocusOnClick = false;
			global::Gtk.Image w42 = new global::Gtk.Image();
			w42.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("NewRestoran.images.back-save.png");
			this.buttonBackAndSave.Image = w42;
			this.vbox2.Add(this.buttonBackAndSave);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonBackAndSave]));
			w43.Position = 6;
			w43.Expand = false;
			w43.Fill = false;
			this.hbox2.Add(this.vbox2);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
			w44.Position = 2;
			w44.Expand = false;
			w44.Fill = false;
			w44.Padding = ((uint)(30));
			this.Add(this.hbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 1242;
			this.DefaultHeight = 613;
			this.hboxSpremljeno.Hide();
			this.vboxFormView.Hide();
			this.Hide();
			this.buttonSearch.Clicked += new global::System.EventHandler(this.OnButtonSearchClicked);
			this.buttonSearchForm.Clicked += new global::System.EventHandler(this.OnButtonSearchClicked);
			this.buttonOdustani.Clicked += new global::System.EventHandler(this.OnButtonOdustaniClicked);
			this.buttonSpremi.Clicked += new global::System.EventHandler(this.OnButtonSpremiClicked);
			this.buttonDodajStol.Clicked += new global::System.EventHandler(this.OnButtonDodajStolClicked);
			this.buttonUp.Clicked += new global::System.EventHandler(this.OnButtonUpClicked);
			this.buttonDown.Clicked += new global::System.EventHandler(this.OnButtonDownClicked);
			this.buttonChange.Clicked += new global::System.EventHandler(this.OnButtonChangeClicked);
			this.buttonDelete.Clicked += new global::System.EventHandler(this.OnButtonDeleteClicked);
			this.buttonBackAndSave.Clicked += new global::System.EventHandler(this.OnButtonBackAndSaveClicked);
		}
	}
}
